#!/bin/sh
# from http://tbaggery.com/2011/08/08/effortless-ctags-with-git.html
set -e
PATH="/usr/local/bin:$PATH"
gitdir="`git rev-parse --git-dir`"
dir=$gitdir/..
trap 'rm -f "$dir/$$.tags"' EXIT
git ls-files | \
  ctags --tag-relative -L - -f"$dir/$$.tags" --languages=-javascript,sql
mv "$dir/$$.tags" "$dir/tags"

